// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGJaqQUJM7qC5tEnxwpvYXWx3XfshTiTU',
    appId: '1:529866034592:web:981916fdab7a2b55e628c5',
    messagingSenderId: '529866034592',
    projectId: 'hw07-63cad',
    authDomain: 'hw07-63cad.firebaseapp.com',
    databaseURL: 'https://hw07-63cad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hw07-63cad.appspot.com',
    measurementId: 'G-242D2RZ3ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3HgzCUlq7IHLnkjOjh08-06ySRA9_INs',
    appId: '1:529866034592:android:7d6bb2cecb5af3f0e628c5',
    messagingSenderId: '529866034592',
    projectId: 'hw07-63cad',
    databaseURL: 'https://hw07-63cad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hw07-63cad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrkb1DI2z3xc9KGFO0t3atSSVchV8t0-4',
    appId: '1:529866034592:ios:a86043594008b4c4e628c5',
    messagingSenderId: '529866034592',
    projectId: 'hw07-63cad',
    databaseURL: 'https://hw07-63cad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hw07-63cad.appspot.com',
    iosClientId: '529866034592-pbr6cce4h1p5tno50hms56de2vo4gg9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.hw7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrkb1DI2z3xc9KGFO0t3atSSVchV8t0-4',
    appId: '1:529866034592:ios:a86043594008b4c4e628c5',
    messagingSenderId: '529866034592',
    projectId: 'hw07-63cad',
    databaseURL: 'https://hw07-63cad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hw07-63cad.appspot.com',
    iosClientId: '529866034592-pbr6cce4h1p5tno50hms56de2vo4gg9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.hw7',
  );
}
